import { Event, Club } from './types';

export const seedClubs: Club[] = [
  {
    id: 'soho-house-chicago',
    name: 'Soho House Chicago',
    type: 'social',
    description: 'Members club for creative professionals with workspace, dining, and events.',
    location: 'West Loop, Chicago',
    address: '113-125 N Green St, Chicago, IL 60607',
    website: 'https://www.sohohouse.com/en-us/houses/soho-house-chicago',
    cost_info: '$2,400-$3,600/year',
    membership_info: 'Application required, focus on creative industries',
    vibe: 'Upscale creative community, stylish interiors, great for creative professionals and media',
    tags: ['creative', 'networking', 'workspace', 'dining', 'upscale'],
    status: 'active',
  },
  {
    id: 'chicago-club',
    name: 'The Chicago Club',
    type: 'professional',
    description: 'Historic private club for business and civic leaders since 1869.',
    location: 'Loop, Chicago',
    address: '81 E Van Buren St, Chicago, IL 60605',
    website: 'https://www.thechicagoclub.org',
    cost_info: 'Invitation only, ~$5,000+ initiation + annual dues',
    membership_info: 'Invitation and sponsorship required, prestigious business leaders',
    vibe: 'Traditional, old-money, business elite, formal dining and events',
    tags: ['business', 'traditional', 'exclusive', 'dining', 'networking'],
    status: 'active',
  },
  {
    id: 'union-league-club',
    name: 'Union League Club of Chicago',
    type: 'professional',
    description: 'Private club with dining, fitness, and event spaces for professionals.',
    location: 'Loop, Chicago',
    address: '65 W Jackson Blvd, Chicago, IL 60604',
    website: 'https://www.ulcc.org',
    cost_info: '$2,000-$4,000/year + initiation fee',
    membership_info: 'Application process, diverse professional membership',
    vibe: 'Professional, civic-minded, strong business network, athletic facilities',
    tags: ['business', 'networking', 'fitness', 'dining', 'events'],
    status: 'active',
  },
  {
    id: 'standard-club',
    name: 'The Standard Club',
    type: 'professional',
    description: 'Historic social and dining club with business networking focus.',
    location: 'Loop, Chicago',
    address: '320 S Plymouth Ct, Chicago, IL 60604',
    website: 'https://www.standardclub.org',
    cost_info: '~$3,000/year + initiation',
    membership_info: 'Application required, diverse professional community',
    vibe: 'Established professionals, great dining, strong Jewish heritage',
    tags: ['business', 'dining', 'networking', 'heritage'],
    status: 'active',
  },
  {
    id: '1871-chicago',
    name: '1871',
    type: 'tech',
    description: "Chicago's premier tech hub and startup incubator with events, workspace, and community.",
    location: 'Merchandise Mart, Chicago',
    address: '222 Merchandise Mart Plaza, Chicago, IL 60654',
    website: 'https://www.1871.com',
    cost_info: 'Membership starts ~$300/month',
    membership_info: 'Open to entrepreneurs, freelancers, and corporate innovators',
    vibe: 'Startup energy, collaboration-focused, tons of events and workshops',
    tags: ['tech', 'startups', 'coworking', 'events', 'innovation'],
    status: 'active',
  },
  {
    id: 'mhub-chicago',
    name: 'mHUB',
    type: 'tech',
    description: 'Hardtech and manufacturing innovation center with prototyping lab and community.',
    location: 'Fulton Market, Chicago',
    address: '965 W Chicago Ave, Chicago, IL 60642',
    website: 'https://www.mhubchicago.com',
    cost_info: 'Membership from $150/month',
    membership_info: 'Open to hardware entrepreneurs, engineers, and makers',
    vibe: 'Maker culture, hardware-focused, collaborative R&D environment',
    tags: ['tech', 'hardware', 'manufacturing', 'prototyping', 'innovation'],
    status: 'active',
  },
  {
    id: 'built-in-chicago',
    name: 'Built In Chicago',
    type: 'tech',
    description: 'Online community and events platform for Chicago tech professionals.',
    location: 'Online + Chicago events',
    address: 'Virtual',
    website: 'https://www.builtinchicago.org',
    cost_info: 'Free',
    membership_info: 'Open to all tech professionals',
    vibe: 'Inclusive tech community, great for job hunting and learning about Chicago tech scene',
    tags: ['tech', 'community', 'jobs', 'events', 'free'],
    status: 'active',
  },
  {
    id: 'ypo-chicago',
    name: 'YPO Chicago',
    type: 'professional',
    description: 'Young Presidents Organization chapter for CEOs and leaders under 45.',
    location: 'Chicago',
    address: 'Various locations',
    website: 'https://www.ypo.org/chapters/ypo-chicago',
    cost_info: '~$15,000/year',
    membership_info: 'CEO/President before age 45, company revenue requirements',
    vibe: 'Elite peer learning, global network, personal and professional development',
    tags: ['ceo', 'leadership', 'exclusive', 'peer-learning', 'global'],
    status: 'active',
  },
  {
    id: 'eo-chicago',
    name: 'EO Chicago',
    type: 'professional',
    description: 'Entrepreneurs Organization for founders and leaders of growing companies.',
    location: 'Chicago',
    address: 'Various locations',
    website: 'https://www.eochicago.com',
    cost_info: '~$6,000/year',
    membership_info: 'Company revenue $1M+, founder/owner',
    vibe: 'Supportive entrepreneur community, peer forums, learning events',
    tags: ['entrepreneur', 'leadership', 'peer-learning', 'growth'],
    status: 'active',
  },
  {
    id: 'industrious-chicago',
    name: 'Industrious Chicago',
    type: 'coworking',
    description: 'Premium coworking spaces with professional amenities and community events.',
    location: 'Multiple Chicago locations',
    address: 'Various (River North, Loop, West Loop)',
    website: 'https://www.industriousoffice.com/locations/chicago',
    cost_info: '$400-$800/month',
    membership_info: 'Open to all professionals',
    vibe: 'Professional, design-forward, quiet and productive',
    tags: ['coworking', 'professional', 'networking', 'workspace'],
    status: 'active',
  },
  {
    id: 'wework-chicago',
    name: 'WeWork Chicago',
    type: 'coworking',
    description: 'Global coworking brand with multiple Chicago locations and regular events.',
    location: 'Multiple Chicago locations',
    address: 'Various (Loop, River North, Fulton Market, etc.)',
    website: 'https://www.wework.com/l/chicago',
    cost_info: '$300-$700/month',
    membership_info: 'Open to all',
    vibe: 'Social, startup-friendly, lots of community events and happy hours',
    tags: ['coworking', 'events', 'social', 'startups', 'workspace'],
    status: 'active',
  },
  {
    id: 'chicago-tech-academy',
    name: 'Chicago Tech Academy',
    type: 'tech',
    description: 'Community of tech professionals and leaders with events and networking.',
    location: 'Chicago',
    address: 'Various event locations',
    website: 'https://www.chicagotechacademy.com',
    cost_info: 'Varies by event',
    membership_info: 'Open to tech community',
    vibe: 'Learning-focused, diverse tech community, skill development',
    tags: ['tech', 'education', 'community', 'events'],
    status: 'active',
  },
];

// No sample events — real events are discovered via API/scrapers on first load
export const seedEvents: Event[] = [
/*
  {
    id: 'sample-1',
    title: 'Chicago Tech Leaders Summit 2026',
    description: 'Annual gathering of Chicago tech executives and engineering leaders. Keynotes, workshops, and networking.',
    start_date: '2026-04-15T09:00:00',
    end_date: '2026-04-15T17:00:00',
    location: 'Navy Pier, Chicago',
    format: 'in-person',
    type: 'conference',
    topics: ['tech', 'leadership', 'engineering'],
    cost: 'paid',
    price: 299.00,
    url: 'https://example.com/tech-summit',
    source: 'sample',
    status: 'active',
  },
  {
    id: 'sample-2',
    title: 'Engineering Manager Roundtable',
    description: 'Monthly peer discussion for engineering managers in Chicago. Share challenges, solutions, and best practices.',
    start_date: '2026-03-20T18:00:00',
    end_date: '2026-03-20T20:00:00',
    location: '1871, Chicago',
    format: 'in-person',
    type: 'meetup',
    topics: ['engineering', 'leadership', 'management'],
    cost: 'free',
    price: 0,
    url: 'https://example.com/em-roundtable',
    source: 'sample',
    status: 'active',
  },
  {
    id: 'sample-3',
    title: 'SaaS Growth Strategies Webinar',
    description: 'Learn proven strategies for scaling SaaS products from 0-$10M ARR. Expert panel and Q&A.',
    start_date: '2026-03-25T14:00:00',
    end_date: '2026-03-25T15:30:00',
    location: 'Virtual',
    format: 'virtual',
    type: 'webinar',
    topics: ['saas', 'business', 'growth'],
    cost: 'free',
    price: 0,
    url: 'https://example.com/saas-growth',
    source: 'sample',
    status: 'active',
  },
  {
    id: 'sample-4',
    title: 'Business Development Workshop: B2B Sales for Engineers',
    description: 'Hands-on workshop teaching technical founders and engineering leaders how to approach B2B sales.',
    start_date: '2026-04-02T10:00:00',
    end_date: '2026-04-02T16:00:00',
    location: 'mHUB, Chicago',
    format: 'in-person',
    type: 'workshop',
    topics: ['business', 'sales', 'engineering'],
    cost: 'paid',
    price: 149.00,
    url: 'https://example.com/bd-workshop',
    source: 'sample',
    status: 'active',
  },
  {
    id: 'sample-5',
    title: 'Chicago Startup Networking Happy Hour',
    description: 'Casual networking event for Chicago startup founders, operators, and investors.',
    start_date: '2026-03-28T17:30:00',
    end_date: '2026-03-28T20:00:00',
    location: 'West Loop, Chicago',
    format: 'in-person',
    type: 'networking',
    topics: ['startups', 'networking', 'business'],
    cost: 'free',
    price: 0,
    url: 'https://example.com/startup-happy-hour',
    source: 'sample',
    status: 'active',
  },
  {
    id: 'sample-6',
    title: 'AI for Product Leaders',
    description: 'Virtual seminar exploring how to integrate AI into product strategy and roadmaps.',
    start_date: '2026-04-10T13:00:00',
    end_date: '2026-04-10T14:30:00',
    location: 'Virtual',
    format: 'virtual',
    type: 'seminar',
    topics: ['ai', 'product', 'tech'],
    cost: 'paid',
    price: 49.00,
    url: 'https://example.com/ai-product',
    source: 'sample',
    status: 'active',
  },
*/
];
